from flask import Flask, request, jsonify, send_file, render_template
from flask_cors import CORS
from flask_mail import Mail, Message
import threading, time, tempfile, os
from datetime import datetime
from osint import full_analysis
from scraper import get_all_urls
from report import generate_pdf
app = Flask(__name__)
CORS(app)

# Mail config
app.config['MAIL_SERVER'] = 'smtp.gmail.com'
app.config['MAIL_PORT'] = 587
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_USERNAME'] = os.getenv('MAIL_USERNAME')
app.config['MAIL_PASSWORD'] = os.getenv('MAIL_PASSWORD')
app.config['MAIL_DEFAULT_SENDER'] = os.getenv('MAIL_USERNAME')
mail = Mail(app)



scan_results = []
auto_scan_running = False
scanned_urls = set()


def auto_scan_loop():
    global scan_results, auto_scan_running, scanned_urls
    while auto_scan_running:
        try:
            print(f"[{datetime.now().strftime('%H:%M:%S')}] Fetching URLs from all sources...")
            urls = get_all_urls()
            new_urls = [u for u in urls if u not in scanned_urls]
            print(f"  Found {len(new_urls)} new URLs to analyze")
            for url in new_urls:
                if not auto_scan_running:
                    break
                print(f"  Analyzing: {url[:60]}...")
                try:
                    result = full_analysis(url)
                    scanned_urls.add(url)
                    scan_results.insert(0, result)
                    scan_results = scan_results[:100]
                    level = result.get('ai_analysis', {}).get('threat_level', '?')
                    print(f"  Done: {level} — {url[:50]}")
                except Exception as e:
                    print(f"  Error: {e}")
                time.sleep(8)
        except Exception as e:
            print(f"Loop error: {e}")
        print("  Waiting 90 seconds...")
        time.sleep(90)


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/start-auto-scan", methods=["POST"])
def start_auto_scan():
    global auto_scan_running
    if not auto_scan_running:
        auto_scan_running = True
        t = threading.Thread(target=auto_scan_loop, daemon=True)
        t.start()
    return jsonify({"status": "running"})


@app.route("/stop-auto-scan", methods=["POST"])
def stop_auto_scan():
    global auto_scan_running
    auto_scan_running = False
    return jsonify({"status": "stopped"})


@app.route("/scan-results")
def get_results():
    return jsonify({
        "results": scan_results,
        "running": auto_scan_running,
        "total": len(scanned_urls)
    })


@app.route("/analyze", methods=["POST"])
def analyze():
    url = request.json.get("url", "")
    result = full_analysis(url)
    scan_results.insert(0, result)
    return jsonify(result)


@app.route("/report", methods=["POST"])
def download_report():
    data = request.json
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        path = f.name
    generate_pdf(data, path)
    return send_file(path, as_attachment=True, download_name="PhishRadar_Report.pdf")

@app.route("/send-report", methods=["POST"])
def send_report():
    try:
        data = request.json
        ai = data.get("ai_analysis", {})
        infra = data.get("infrastructure", {})
        vt = data.get("virustotal", {})
        recipient = data.get("recipient_email", os.getenv("REPORT_EMAIL"))

        # Generate PDF
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
            pdf_path = f.name
        generate_pdf(data, pdf_path)

        # Build email body
        body = f"""
PHISHRADAR — CYBER FRAUD THREAT INTELLIGENCE REPORT
====================================================
This is an automated report generated by PhishRadar.

THREAT DETAILS
--------------
URL Analyzed    : {data.get('url', 'N/A')}
Threat Level    : {ai.get('threat_level', 'N/A')}
Threat Type     : {ai.get('threat_type', 'N/A')}
AI Confidence   : {ai.get('confidence', 0)}%
Timestamp       : {data.get('timestamp', 'N/A')}

INFRASTRUCTURE
--------------
Domain          : {infra.get('domain', 'N/A')}
IP Address      : {infra.get('ip_address', 'N/A')}
Country         : {infra.get('country', 'N/A')}
Hosting Provider: {infra.get('org', 'N/A')}
ISP             : {infra.get('isp', 'N/A')}
Registrar       : {infra.get('registrar', 'N/A')}
Domain Created  : {infra.get('domain_created', 'N/A')}

VIRUSTOTAL RESULTS
------------------
Malicious       : {vt.get('malicious', 0)} engines
Suspicious      : {vt.get('suspicious', 0)} engines
Harmless        : {vt.get('harmless', 0)} engines

AI THREAT SUMMARY
-----------------
{ai.get('summary', 'N/A')}

INDICATORS OF COMPROMISE
------------------------
{chr(10).join(['• ' + i for i in ai.get('indicators', [])])}

C2 ASSESSMENT
-------------
{ai.get('c2_likelihood', 'N/A')}

RECOMMENDED ACTION
------------------
{ai.get('recommended_action', 'N/A')}

====================================================
This report was automatically generated by PhishRadar.
For more information contact your cybercrime unit.
====================================================
        """

        # Send email with PDF attached
        msg = Message(
            subject=f"🚨 PhishRadar Alert: {ai.get('threat_level', 'UNKNOWN')} Threat Detected — {infra.get('domain', 'Unknown Domain')}",
            recipients=[recipient],
            body=body
        )

        # Attach PDF
        with open(pdf_path, 'rb') as f:
            msg.attach(
                filename=f"PhishRadar_Report_{infra.get('domain', 'threat')}.pdf",
                content_type="application/pdf",
                data=f.read()
            )

        # Attach screenshot if available
        if data.get("screenshot"):
            import base64
            img_data = base64.b64decode(data["screenshot"])
            msg.attach(
                filename="phishing_screenshot.png",
                content_type="image/png",
                data=img_data
            )

        mail.send(msg)
        return jsonify({"status": "success", "message": f"Report sent to {recipient}"})

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500
if __name__ == "__main__":
    app.run(debug=True, port=5000)